name: Build and Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cloud Run Deploy
      uses: georgemblack/actions/cloud-run-deploy@1.0.4
      with:
        serviceName: aaron-web
        projectId: ${{ secrets.GCLOUD_PROJECT_ID }}
        runtimeServiceAccount: ${{ secrets.GCLOUD_RUNTIME_SERVICE_ACCOUNT }}
        cloudBuildBucket: artifacts.georgemb.appspot.com
        concurrency: 20
        maxInstances: 800
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}